site_name: Botgen

nav:
  - Home: index.md
  - Introduction: intro.md
  - Conversation: conversation.md

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_name: jpfcabral/botgen
repo_url: https://github.com/jpfcabral/botgen
