name: Tests

on: [push]

jobs:
  unittests:
  name: Unit tests
  steps:
  - uses: actions/checkout@v4
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.11'
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip poetry
      poetry install
  - name: Unit test with pytest
    run: |
      poetry run pytest tests/ -vs --cov botgen/ --cov-report term-missing
